---
- name: create syseng groups
  group:
    name: "{{ item }}"
  with_items: "{{ syseng_access_groups }}"

- name: create syseng users
  user:
    name: "{{ item.username }}"
    groups: "{{ syseng_access_groups | join(',') }}"
    append: yes
    shell: /bin/bash
  with_items: "{{ syseng_access_users }}"

- name: import user ssh-keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', '{{ item.pubkey }}') }}"
    exclusive: yes
  with_items: "{{ syseng_access_users }}"
  ignore_errors: "{{ ansible_check_mode }}"

# Confirm include directory exists with the proper permissions
- name: create /etc/sudoers.d dir
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0750
    state: directory

- name: configure syseng sudo rights
  template:
    src: sudoers.d/sysengadmins
    dest: /etc/sudoers.d/sysengadmins
    owner: root
    group: root
    mode: 0400

# Confirm include directory exists in /etc/sudoers
- name: configure sudoers include directory
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^#includedir \/etc\/sudoers.d'
    line: '#includedir /etc/sudoers.d'
