---
# Support for post-transaction-action on package changes
- name: install yum-plugin-post-transaction-actions
  package:
    name: yum-plugin-post-transaction-actions
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version < '8'

# Action to update log directory permissions on any package updates
- name: install post-transaction-action for yum
  template:
    src: nginx.action.j2
    dest: /etc/yum/post-actions/nginx.action
    owner: root
    group: root
    mode: 0600
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version < '8'

# This may not be needed in newer versions. 
# Nginx 1.18 seemed to install on CentOS 8 with the desired directory permissions already
- name: create /etc/nginx/ssl dir
  file:
    path: /etc/dnf/plugins/post-transaction-actions.d
    owner: root
    group: root
    mode: 0655
    state: directory
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version >= '8'
- name: install post-transaction-action for dnf
  template:
    src: nginx.action.j2
    dest: /etc/dnf/plugins/post-transaction-actions.d/nginx.action
    owner: root
    group: root
    mode: 0600
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version >= '8'





- name: install nginx
  yum: name=nginx

- name: install httpd-tools
  package: name=httpd-tools

- name: Ensure default php-fpm config file is not in nginx/default.d directory
  file:
    path: /etc/nginx/default.d/php.conf
    state: absent
- name: Ensure default php-fpm config file is not in nginx/conf.d directory
  file:
    path: /etc/nginx/conf.d/php-fpm.conf
    state: absent

- import_tasks: configure-nginx.yml
- import_tasks: configure-ssl.yml
- import_tasks: configure-logrotate.yml

- name: start nginx service
  service:
    name: nginx
    state: started
    enabled: true

# Reload nginx now if nginx.conf was touched; this allows nginx to disassociate with previous user if needed
- name: reload nginx service
  debug:
    msg: "reloading nginx"
  notify: reload nginx
  when: nginx_conf_result|default(false) and nginx_conf_result is changed
