---
- name: configure vhost {{ vhost_name }}
  template:
    src: "{{ vhost_template }}"
    dest: /etc/nginx/conf.d/{{ vhost_name }}.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nginx
