---
dependencies:
  - { role: classyllama.repo_ius, when: use_classyllama_repo_ius | default(true) }
  - { role: geerlingguy.repo-remi, when: use_geerlingguy_repo_remi | default(false) }  
  - { role: classyllama.repo-redis-appstream, when: use_classyllama_repo_redis_appstream | default(false) }
galaxy_info:
  role_name: multi_redis
  author: David Alger
  description: Multi Redis Deployment on RHEL / CentOS Linux
  license: MIT
  min_ansible_version: 2.4

  platforms:
    - name: EL
      versions:
        - 8
        - 7
        - 6

  galaxy_tags:
    - system
    - redis
