---
- name: reload systemd configuration
  systemd: daemon_reload=yes

- name: restart redis
  service:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ redis_service_restart }}"
  ignore_errors: "{{ ansible_check_mode }}"
