---

- name: include default variables
  include_vars: "../vars/main.yml"

- name: install cachetool
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    checksum: "{{ item.checksum }}"
    timeout: 300
    mode: 0755
  loop:
    - "{{ cachetool_download }}"

- name: create cachetool tmpdir
  file:
    path: "{{ cachetool_config_item.temp_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items: "{{ cachetool_config }}"
  loop_control:
    loop_var: cachetool_config_item
    label: "{{ cachetool_config_item.path }}"

- name: configure cachetool
  template:
    src: cachetool.yml.j2
    dest: "{{ cachetool_config_item.path }}/.cachetool.yml"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ cachetool_config }}"
  loop_control:
    loop_var: cachetool_config_item
    label: "{{ cachetool_config_item.path }}"
