---
- name: test nginx config before restart
  shell: nginx -t
  listen:
    - "restart nginx"
  notify: execute nginx restart

- name: execute nginx restart
  service: name=nginx state=restarted

- name: test nginx config before reload
  shell: nginx -t
  listen:
    - "reload nginx"
  notify: execute nginx reload

- name: execute nginx reload
  service: name=nginx state=reloaded
