---
# This is used in varnish_reload_vcl.j2 to eliminate rhel 6 / 7 dedicated copy of template
- name: set fact varnish_params_dest
  set_fact: varnish_params_dest=/etc/sysconfig/varnish-{{ varnish_instance.name }}

- name: configure varnish-{{ varnish_instance.name }} service
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: configure-el6/sysconfig/varnish.j2
      dest: /etc/sysconfig/varnish-{{ varnish_instance.name }}
      mode: "0644"
    - src: configure-el6/init.d/varnish.j2
      dest: /etc/init.d/varnish-{{ varnish_instance.name }}
      mode: "0755"
    - src: "{{ varnish_vcl_template }}"
      dest: /etc/varnish/varnish-{{ varnish_instance.name }}.vcl
      mode: "0755"
    
    # The varnish_reload_vcl is not needed in newer versions of Varnish 6.0+
    - src: configure/varnish_reload_vcl.j2
      dest: /usr/sbin/varnish_reload_vcl-{{ varnish_instance.name }}
      mode: "0755"
  register: varnish_config
  notify: restart varnish
