---
- name: Database Server Role
  hosts: db
  become: true

  tasks:
    
    # Global Services
    - ansible.builtin.import_role:
         name: classyllama.percona
      tags: mysql
      when: use_classyllama_percona | default(false)
    
    - ansible.builtin.import_role:
         name: classyllama.mariadb
      tags: mysql
      when: use_classyllama_mariadb | default(false)
    
    # Install Additional Tools
    - ansible.builtin.import_role:
         name: classyllama.dbbackup
     tags: dbbackup
     when: use_classyllama_dbbackup | default(false)
    
    # --- Create Databases
    - ansible.builtin.include_tasks: tasks/database-create.yml
      tags: database
      vars:
        mysql_db: "{{ mysql_database.db_name }}"
        mysql_host: "{{ mysql_database.user_host }}"
        mysql_user: "{{ mysql_database.user_name }}"
      loop: '{{ mysql_databases }}'
      loop_control:
        loop_var: mysql_database

    - ansible.builtin.include_tasks: tasks/database-mycnf.yml
      tags: database
      vars:
        mycnf_file: "{{ mysql_database.mycnf_file }}"
        mycnf_opts: "{{ mysql_user_info[mysql_database.user_name] }}"
      loop: '{{ mysql_databases }}'
      loop_control:
        loop_var: mysql_database

    - name: Run all notified handlers
      meta: flush_handlers
      tags: database
