---
- name: Redis Server Role
  hosts: redis
  become: true

  tasks:

    # Environment Specific Services (optionally multiple instances)
    - ansible.builtin.include_role:
         name: classyllama.multi-redis
         apply:
           tags:
             - redis
      tags: redis
      vars:
        redis_instance:
          name: "{{ each_instance.role_vars.redis_instance.name }}"
          port: "{{ each_instance.role_vars.redis_instance.port }}"
          save: "{{ each_instance.role_vars.redis_instance.save | default(false) }}"
        redis_maxmemory: "{{ each_instance.role_vars.redis_maxmemory | default(redis_maxmemory_default) }}"
        redis_instance_config: "{{ each_instance.role_vars.redis_instance_config | default([]) }}"
      loop: '{{ redis_instances }}'
      loop_control:
        loop_var: each_instance
      when: use_classyllama_multi_redis | default(false)
