---
- name: configure redis-{{ redis_instance.name }} service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: redis/redis.conf
      dest: /etc/redis/redis-{{ redis_instance.name }}.conf
      mode: "0644"
    - src: redis.service.j2
      dest: /etc/systemd/system/redis-{{ redis_instance.name }}.service
      mode: "0644"
  register: redis_config_changed
  notify:
    - reload systemd configuration
    - restart redis
