---

# Download links and checksums found at https://getcomposer.org/download/
_composer_download:
  1.9.3:
    url: "https://getcomposer.org/download/1.9.3/composer.phar"
    dest: "/var/cache/ansible/composer-1.9.3.phar"
    checksum: "sha256:551655c2fc81f4106508f42bbc4b24eabd34b022b13bc1e7d9642bf483d0a7d4"
  1.9.1:
    url: "https://getcomposer.org/download/1.9.1/composer.phar"
    dest: "/var/cache/ansible/composer-1.9.1.phar"
    checksum: "sha256:1f210b9037fcf82670d75892dfc44400f13fe9ada7af9e787f93e50e3b764111"
  1.10.17:
    url: "https://getcomposer.org/download/1.10.17/composer.phar"
    dest: "/var/cache/ansible/composer-1.10.17.phar"
    checksum: "sha256:6fa00eba5103ce6750f94f87af8356e12cc45d5bbb11a140533790cf60725f1c"
