---

- ansible.builtin.import_playbook: playbooks/check_ansible_version.yml
- ansible.builtin.import_playbook: playbooks/common.yml

- ansible.builtin.import_playbook: playbooks/web.yml
  when: inventory_hostname in groups['web']

- ansible.builtin.import_playbook: playbooks/elasticsearch.yml
  when: inventory_hostname in groups['elasticsearch']

- ansible.builtin.import_playbook: playbooks/multiredis.yml
  when: inventory_hostname in groups['redis']

- ansible.builtin.import_playbook: playbooks/datadog-web.yml
  when: inventory_hostname in groups['datadog-web']

- ansible.builtin.import_playbook: playbooks/datadog-db.yml
  when: inventory_hostname in groups['datadog-db']
