---
- name: include php-opcache default settings
  include_vars: opcache.yml

# php72u-mcrypt is not a valid package, so remove it from module list on PHP 7.2
- name: drop mcrypt ext when depoying 7.2 or later versions
  set_fact:
    php_default_modules: "{{ php_default_modules | difference(['mcrypt']) }}"
  when: php_version >= 72

# php72u-sodium is the only package for sodium available, remove it from module list on PHP 7.1 and earlier
- name: drop sodium ext when depoying 7.1 or earlier versions
  set_fact:
    php_default_modules: "{{ php_default_modules | difference(['sodium']) }}"
  when: php_version < 72




# php73-xdebug is not a valid package, so replace it with php73-pecl-xdebug on PHP 7.3
- name: replace xdebug with pecl-xdebug ext when deploying 7.3 or later versions
  set_fact:
    php_default_modules: "{{ php_default_modules | difference(['xdebug']) + [ 'pecl-xdebug' ] }}"
  when: php_version >= 73 and 'xdebug' in php_default_modules
- name: replace xdebug with pecl-xdebug ext when deploying 7.3 or later versions
  set_fact:
    php_additional_modules: "{{ php_additional_modules | difference(['xdebug']) + [ 'pecl-xdebug' ] }}"
  when: php_version >= 73 and 'xdebug' in php_additional_modules

# php73-mhash is not a valid package, so remove it from module list on PHP 7.3
- name: drop 'mhash', 'curl', 'xsl', 'zip' ext when deploying 7.3 or later versions (php_modules)
  set_fact:
    php_additional_modules: "{{ php_additional_modules | difference(['mhash', 'curl', 'xsl', 'zip']) }}"
  when: php_version >= 73


- debug:
    var: php_version
- debug:
    var: php_default_modules
- debug:
    var: php_additional_modules
- debug:
    var: php_modules






- name: create {{ php_fpm_owner }} user
  user:
    name: "{{ php_fpm_owner }}"
    state: present

# There is no guarantee this group belongs to the above user, so make sure it exists as well
- name: create {{ php_fpm_group }} group
  group:
    name: "{{ php_fpm_group }}"
    state: present





- name: drop u from IUS package name
  set_fact:
    php_package_name_extra: "{{ php_version }}"
  when: php_enablerepo == "ius" and php_version >= 73 and php_package_name_extra == (php_version ~ "u")

- debug:
    var: php_package_name_extra

- name: Build array of package names to install with yum
  set_fact:
    php_yum_packages: "{{ php_yum_packages|default([]) }} + [ 'php{{ php_package_name_extra }}-{{ item }}' ]"
  with_items: "{{ php_modules }}"
  

- debug:
    var: php_yum_packages







- name: install php-fpm
  yum: 
    name: php{{ php_package_name_extra }}-fpm
    enablerepo: "{{ php_enablerepo }}"

- name: install php modules
  yum: 
    name: "{{ php_yum_packages }}"
    enablerepo: "{{ php_enablerepo }}"

- name: combine php-opcache defaults user provided settings
  set_fact:
    php_ext_opcache: "{{ php_ext_opcache_defaults | combine(php_ext_opcache) }}"

- name: configure php.ini
  ini_file:
    dest: /etc/php.ini
    section: PHP
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ php_fpm_global_ini }}"
  notify: restart php-fpm

- name: configure php.d/10-opcache.ini
  template:
    src: php.d/10-opcache.ini.j2
    dest: /etc/php.d/10-opcache.ini
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm

- name: clear default pool
  template:
    src: www.conf
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0600
  notify: reload php-fpm

- name: "{{ php_fpm_pool }} : configure php-fpm pool"
  template:
    src: pool.conf
    dest: /etc/php-fpm.d/{{ php_fpm_pool }}.conf
    owner: root
    group: root
    mode: 0600
  notify: reload php-fpm

- import_tasks: pecl_packages.yml
  when: php_pecl_packages | length > 0

- import_tasks: configure-logs.yml

- name: start php-fpm
  service:
    name: php-fpm
    state: started
    enabled: true
